### ISSUE TITLE
Rename package name from `azure_functions` to `azure.functions`

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/module-ballerinax-azure.functions#628]
The current package name does not follow Ballerina package naming guidelines.

**Comment by sameerajayasoma** [comment]
We may have to release a new major version

**Comment by xlight05** [comment]
With the following PR, It will create a new package with the name "azure.functions" on release with package version `4.0.0`. If we decide to do this breaking change with update5, the new package will not be resolved by older dist versions.

I believe then we need to do something about the old "azure_functions" package. This will be pulled for distributions below 2201.4.0 and below(which is okay). However, there are a few concerns. 
1. Should we do some kind of deprecate notice?
1. The package will be displayed under ballerinax in central UI. This might confuse some of the users. 
2. Update 5 users might use old "azure_functions" package. 

For issue 1, since `bal deprecate` is only being released with update 5, we can't use that feature. maybe we can print a warning saying package name will be changed from update 5.

For issue 2, One thing we can do is to push a new package (3.2.x) with modified Package.md to with deprecate notice. Are there anything else we can do?

For issue 3, We can print a warning if the user uses old package in update 5. But this has go hand in hand with issue 1.


Not directly related to azure functions package but I feel like its better to do this effort along with other ballerinax packages. (awslambda and others) otherwise, users will face breaking changes like this in different dist updates. Tagging @NipunaRanasinghe as well.
